/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-west-2',
  aws_cognito_region: 'us-west-2',
  aws_user_pools_id: 'us-west-2_q6Zp3ruOT',
  aws_user_pools_web_client_id: 'fuo5gfb72gtan1qfvbpddflj9',
  oauth: {
    domain: 'caramel-dev.auth.us-west-2.amazoncognito.com',
    scope: ['email', 'openid', 'phone', 'profile'],
    redirectSignIn: 'https://www.drivecaramel.com/',
    redirectSignOut: 'https://www.drivecaramel.com/',
    responseType: 'code',
  },
  federationTarget: 'COGNITO_USER_POOLS',
  aws_cognito_username_attributes: ['PHONE_NUMBER'],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: [
    'GIVEN_NAME',
    'FAMILY_NAME',
    'EMAIL',
    'PHONE_NUMBER',
  ],
  aws_cognito_mfa_configuration: 'OPTIONAL',
  aws_cognito_mfa_types: ['SMS', 'TOTP'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [
      'REQUIRES_LOWERCASE',
      'REQUIRES_UPPERCASE',
      'REQUIRES_SYMBOLS',
    ],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
};

export default awsmobile;
